spring.application.name=vincula-poa
spring.datasource.url=jdbc:postgresql://localhost:5432/vincula_poa
spring.datasource.username=postgres
spring.datasource.password=soller123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true