package com.vincula.enums;

public enum TipoAcaoAuditoria {
    DEMANDA_CRIADA,
    DEMANDA_ATUALIZADA,
    DEMANDA_VISUALIZADA,
    DEMANDA_ENCERRADA,
    DEMANDA_REDIRECIONADA,
    DEMANDA_STATUS_ALTERADO,
    DEMANDA_DELETADA,

    TENTATIVA_CONTATO_CRIADA,
    TENTATIVA_CONTATO_ATUALIZADA,
    TENTATIVA_CONTATO_VISUALIZADA,
    TENTATIVA_CONTATO_DELETADA,

    PACIENTE_CRIADO,
    PACIENTE_ATUALIZADO,
    PACIENTE_VISUALIZADO,
    PACIENTE_DELETADO,

    USUARIO_CRIADO,
    USUARIO_ATUALIZADO,
    USUARIO_SENHA_ALTERADA,
    USUARIO_VISUALIZADO,
    USUARIO_DELETADO,

    UNIDADE_SAUDE_CRIADA,
    UNIDADE_SAUDE_ATUALIZADA,
    UNIDADE_SAUDE_VISUALIZADA,
    UNIDADE_SAUDE_DELETADA,

    OBSERVACAO_CRIADA,
    OBSERVACAO_ATUALIZADA,
    OBSERVACAO_VISUALIZADA,
    OBSERVACAO_DELETADA,

    ENDERECO_CRIADO,
    ENDERECO_ATUALIZADO,
    ENDERECO_VISUALIZADO,
    ENDERECO_DELETADO,

    LOGIN_REALIZADO,
    LOGIN_FALHOU,
    LOGOUT_REALIZADO,

    EMAIL_ENVIADO,
    EMAIL_FALHOU,

    EXPORTACAO_CSV_REALIZADA,
    DASHBOARD_ACESSADO,

    ALTERACAO_SENHA,
    ACESSO_NEGADO,
}