package com.vincula.enums;

public enum TipoAcaoAuditoria {
    DEMANDA_CRIADA,
    DEMANDA_ATUALIZADA,
    DEMANDA_ENCERRADA,
    DEMANDA_REDIRECIONADA,

    TENTATIVA_CONTATO_CRIADA,
    TENTATIVA_CONTATO_ATUALIZADA,
    TENTATIVA_CONTATO_DELETADA,

    PACIENTE_CRIADO,
    PACIENTE_ATUALIZADO,
    PACIENTE_DELETADO,

    USUARIO_CRIADO,
    USUARIO_ATUALIZADO,
    USUARIO_DELETADO,

    UNIDADE_SAUDE_CRIADA,
    UNIDADE_SAUDE_ATUALIZADA,
    UNIDADE_SAUDE_DELETADA,

    OBSERVACAO_CRIADA,
    OBSERVACAO_ATUALIZADA,
    OBSERVACAO_DELETADA,

    ENDERECO_CRIADO,
    ENDERECO_ATUALIZADO,
    ENDERECO_DELETADO,

    LOGIN_REALIZADO,
    LOGIN_FALHOU,

    EMAIL_ENVIADO

}